### ISSUE TITLE
Which exit to take?

### ISSUE THREAD

**Issue by daryltan888** [daryltan888/OOP-Project#3]
Commuters want to know which exit to take when they are at an MRT station with many exits.

**Comment by bryanlmx** [comment]
Acceptance criteria:
- Cover the MRT stations with more traffic or are interchanges like Bugis and Chinatown
- Be clear and concise, do not over clutter
- Show if exits are wheelchair accessible

**Comment by daryltan888** [comment]
Acceptance Criteria:
1) The commuters will like to know which exits lead to which facilities so that they do not waste time going to the wrong exit.
2) The commuters will like to know which bus services are located near MRT stations so that they get to their destination.

**Comment by daryltan888** [comment]
Done Criteria:
1. Unit testing completed.
2. Functional testing completed.
