### ISSUE TITLE
Alternative routes

### ISSUE THREAD

**Issue by daryltan888** [daryltan888/OOP-Project#5]
The working adults want to know the alternative routes (bus) to a destination.

**Comment by bryanlmx** [comment]
Acceptance Criteria:
- Compare the timings of routes and also number of transfers
- Compare cost
- Clear and concise, presented neatly in a table.

**Comment by daryltan888** [comment]
Acceptance Criteria:
1) The working adults will like to know which bus services they should take if a train disruption occurs so that they will not waste time finding out by themselves.
2) The working adults will like to know the fastest way of reaching a destination so that they will save much time.

**Comment by daryltan888** [comment]
Done Criteria:
1. Unit testing completed.
2. Functional testing completed.
